import remarkGfm from 'remark-gfm';
import remarkLint from 'remark-lint';
import remarkFrontmatter from 'remark-frontmatter';
import remarkLintBlockquoteIndentation from 'remark-lint-blockquote-indentation';
import remarkLintCheckboxCharacterStyle from 'remark-lint-checkbox-character-style';

export default {
  plugins: [
    remarkGfm,
    remarkLint,
    [remarkFrontmatter, { type: 'yaml', marker: '-' }],
    [remarkLintBlockquoteIndentation, 2],
    [remarkLintCheckboxCharacterStyle, ['warn', { checked: 'x', unchecked: ' ' }]],
    ['remark-lint-checkbox-content-indent', 'warn'],
    ['remark-lint-code-block-style', ['warn', 'fenced']],
    ['remark-lint-emphasis-marker', ['warn', '*']],
    ['remark-lint-fenced-code-marker', ['warn', '`']],
    ['remark-lint-file-extension', ['error', 'md']],
    ['remark-lint-final-newline', 'warn'],
    ['remark-lint-first-heading-level', ['warn', 2]],
    ['remark-lint-hard-break-spaces'],
    ['remark-lint-heading-increment', 'warn'],
    ['remark-lint-heading-style', ['warn', 'atx']],
    ['remark-lint-link-title-style', '\''],
    ['remark-lint-list-item-bullet-indent', 'warn'],
    ['remark-lint-list-item-indent', ['warn', 'space']],
    ['remark-lint-list-item-spacing', ['warn', { checkBlanks: true }]],
    ['remark-lint-no-blockquote-without-marker', 'warn'],
    ['remark-lint-no-consecutive-blank-lines', 'warn'],
    ['remark-lint-no-duplicate-definitions'],
    ['remark-lint-no-duplicate-headings'],
    ['remark-lint-no-empty-url'],
    ['remark-lint-no-file-name-articles'],
    ['remark-lint-no-file-name-consecutive-dashes'],
    ['remark-lint-no-file-name-outer-dashes'],
    ['remark-lint-no-heading-content-indent', 'warn'],
    ['remark-lint-no-heading-indent', 'warn'],
    ['remark-lint-no-inline-padding', 'warn'],
    ['remark-lint-no-missing-blank-lines', ['warn', { exceptTightLists: true }]],
    ['remark-lint-no-paragraph-content-indent', 'warn'],
    ['remark-lint-no-table-indentation', 'warn'],
    ['remark-lint-ordered-list-marker-style', ['warn', '.']],
    ['remark-lint-ordered-list-marker-value', 'ordered'],
    ['remark-lint-strikethrough-marker', '~~'],
    ['remark-lint-strong-marker', '*'],
    ['remark-lint-table-pipe-alignment'],
    ['remark-lint-table-pipes'],
    ['remark-lint-unordered-list-marker-style', ['warn', '-']],
    ['remark-lint-no-empty-sections'],
    ['remark-stringify', {
      bullet: '-',
      bulletOther: '*',
      bulletOrdered: '.',
      closeAtx: false,
      emphasis: '*',
      fence: '`',
      fences: true,
      incrementListMarker: true,
      listItemIndent: 'one',
      quote: '\'',
      resourceLink: false,
      rule: '-',
      ruleRepetition: 3,
      ruleSpaces: false,
      setext: false,
      strong: '*',
    }],
  ],
};
